### ISSUE TITLE
To support modular architecture for workflow steps

### ISSUE THREAD

**Issue by fyhao** [fyhao/electron-wf#5]
To support modular architecture for workflow steps, to ease creation, maintenance of new step module easily by placing the module code in another sub module folder or file.

Proposed changes and requirements
------

- Have a new folder, named lib, and another folder, named steps under the lib folder.
- Create a step bootstrapping process which will scan the step definition file in:
  - single step definition file in /lib/steps/ folder, say lib/steps/setVar.js, lib/steps/if.js
  - step definition folder in /lib/steps folder, say lib/steps/setVar/init.js, lib/steps/if/init.js
  - step definition folder in top level node_modules, with following rules:
    - node_modules name, starts as electron-wf-step-<your step name>
    - there is a file called electron-wf-step-module.json, which contains following module definition:
      - `{ name: 'electron-wf-step-<your step name>', version:'1.0', author: '', email: '', license: ''}`
  - The step name must be unique, and must give warning and exit the program when found duplicate.

- For each step definition file it should have module.exports to provide following interfaces:
  - spec
  **description**: to provide spec and description of the steps
  **type**: function
  **input**: none
  **output**: json
  json should contains an object
  `
{
  description: '<the step description>',
  name : 'setVar',
  fields : [
  {type: 'string', name:'name', description: 'the name of the variable', required:true},
  {type: 'string', name:'value', description: 'the value of the variable', required:true}
]
}
`

  - process
  **description**: to process a runtime step in workflow, after finished running the step, must call next() function to proceed to next step.
  **type**: function
  **input**: a runtime step object, and a next function
  **output**: none

- Create step processing routine which will:
  - Scan available steps definition list, and if found by the step name,
  - Check against step definition spec, to see if all the required fields are there, check required, and name attribute for now. Do not check type field yet, type field just for info purpose.

- To pass workflow running context object into step processing routine.
  Include vars object at least attached inside the context object.

**Task Checklist**
------

- [x] Create new folder lib/steps
- [x] Create new code file named step.js, for step bootstrapping process, called from tests.js
- [x] step.js to have module.exports expose interface - bootstrap()
- [x] step.js to process single step definition file in /lib/steps folder.
- [x] step.js to process step definition folder in /lib/steps folder
- [ ] step.js to process step definition folder in top level node_modules
- [x] step.js to handle duplicate step name scenario
- [x] in tests.js, during workflow running process, integrate to step.js to find available steps run, by having step.js expose interface - processStep(step, next)
- [x] step.js processStep function to scan available step definition in the list.
- [x] step.js processStep function check and compare with the step definition spec, check required and name attribute only.
- [x] step.js processStep function to perform the actual step's task by calling process(step, next) function in step definition file.
- [x] create context object in tests.js when processing workflow.
- [x] make sure vars object and another necessary items attached into context object and passed into step.js processStep function.

**Regression Test and Migration Checklist:**
------

Big Task
------
- [x] 1) Implement all steps file with working process function (done)
- [x] 2) Implement all steps file with working spec function, check required fields

Modules
------
- [x] log
- [x] exec
- [x] setVar
- [x] incrementVar
- [x] replaceAll
- [x] if
- [x] testDataPrep
- [x] copyFile
- [x] copyFolder
- [x] createFolder
- [x] deleteFolder
- [x] deleteFile
- [x] openFileRead
- [x] openFileWrite
- [x] appendFileWrite
- [x] printlnFileWrite
- [x] closeFileWrite
- [x] openExcel
- [x] readExcelCell
- [x] writeExcelCell
- [x] saveExcel
- [x] runExcelCase
- [x] wsread
- [x] wsupdate
- [x] sql
- [x] xml
- [x] evaljs
- [x] Execute sub flow (search available work flow) inputVars, outputVars
- [x] Execute sub flow inputall, outputall special functions

**Comment by fyhao** [comment]
Think I should create one test case file which will test almost all the steps during development and testing

**Comment by fyhao** [comment]
working in progress for big task: Implement all steps file with working process function

**Comment by fyhao** [comment]
done for big task 1 & 2 for all steps module

**Comment by fyhao** [comment]
Checked testDataPrep
Pending node_modules scanning
